version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    entrypoint: ["sh", "/usr/src/app/docker-entrypoint.sh"]
